[Settings]
# Note - I believe these are overriden in the UI
ID = "docs.dennisokeeffe.com"

[build]
  # command = "yarn build" - build local now since timeout occurs
  publish = "build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
